### ISSUE TITLE
Making Contact 

### ISSUE THREAD

**Issue by ghost** [mountainstorm/CoreSymbolication#1]
Hi Rich, do you have an email address I can get you on? I have some questions regarding compiling DTrace on OSX. 

Thanks
Ray

**Comment by mountainstorm** [comment]
Well I never actually finished my effort to get CoreSymbolication compiling; I was planning to but I ended up trying something else - the tracer on my github.

So I probably can't help you much.  Did you have any specific queries ... I might have some recollection from when I was trying?

Rich
